services:
    bsadnu.grand_id:
        alias: Bsadnu\GrandIDBundle\Services\GrandID
        public: true
    Bsadnu\GrandIDBundle\Services\GrandID:
        public: false
        arguments:
            - '%bsadnu.grand_id.config%'