services:
    develit_ab.grand_id:
        alias: DevelitAB\GrandIDBundle\Services\GrandID
        public: true
    DevelitAB\GrandIDBundle\Repository\GrandIdSessionRepository:
        autowire: true
        public: false
        tags: ['doctrine.repository_service']        
    DevelitAB\GrandIDBundle\Services\GrandID:
        public: false
        arguments:
            - '%develit_ab.grand_id.config%'
            - '@doctrine.orm.entity_manager'
